import { Recipe } from '@shared/entities/recipe.model';

export const RECIPES_MOCK: Array<Recipe> = [
  {
    id: '01',
    name: 'Amatriciana',
    servings: 4,
    prepTimeMinutes: 35,
    ingredients: [
      { name: 'guanciale (o panceta ahumada)', quantity: 200, unit: 'g' },
      {
        name: 'pasta (bucatini es la opción tradicional)',
        quantity: 400,
        unit: 'g',
      },
      {
        name: 'tomates pelados en lata (o tomates cherry frescos)',
        quantity: 400,
        unit: 'g',
      },
      {
        name: 'cebolla pequeña o media cebolla grande, finamente picada (opcional)',
        quantity: 1,
        unit: 'unidad',
      },
      { name: 'vino blanco', quantity: 50, unit: 'ml' },
      { name: 'guindilla entera (opcional)', quantity: 1, unit: 'unidad' },
      {
        name: 'aceite de oliva virgen extra (opcional)',
        unit: 'al gusto',
      },
      { name: 'sal', unit: 'al gusto' },
      {
        name: 'pecorino romano rallado (preferible) o Parmigiano-Reggiano',
        unit: 'al gusto',
      },
    ],
    instructions: [
      'Cortar el guanciale (o la panceta) en tiras finas.',
      'Calentar una sartén sin aceite y agregar el guanciale. Cocinar a fuego medio hasta que suelte su grasa y se dore ligeramente. Agregar la guindilla si se desea.',
      'Retirar el guanciale y dejar parte de la grasa para cocinar la cebolla con sal. Cocinar hasta transparente (5-7 min).',
      'Añadir el vino blanco y evaporar el alcohol completamente.',
      'Agregar los tomates triturados o cherry y cocinar (10-20 min según el tipo).',
      'Cocer la pasta al dente según el paquete.',
      'Reservar un poco de agua de cocción y añadir a la salsa para ligar.',
      'Agregar la pasta a la sartén con la salsa y mezclar bien.',
      'Servir con queso pecorino rallado.',
    ],
  },
  {
    id: '02',
    name: 'Pesto',
    servings: 4,
    prepTimeMinutes: 30,
    ingredients: [
      { name: 'espaguetis', quantity: 350, unit: 'g' },
      { name: 'hojas de albahaca fresca', quantity: 2, unit: 'tazas' },
      { name: 'queso parmesano rallado', quantity: 0.5, unit: 'taza' },
      { name: 'piñones (o nueces)', quantity: 0.25, unit: 'taza' },
      { name: 'dientes de ajo', quantity: 2, unit: 'unidad' },
      { name: 'aceite de oliva extra virgen', quantity: 0.5, unit: 'taza' },
      { name: 'sal', unit: 'al gusto' },
      { name: 'pimienta negra molida', unit: 'al gusto' },
    ],
    instructions: [
      'Hervir agua con sal y cocinar los espaguetis al dente.',
      'En procesador o mortero, mezclar albahaca, queso, piñones y ajo.',
      'Agregar el aceite en hilo fino hasta obtener una salsa homogénea. Salpimentar.',
      'Mezclar el pesto con la pasta caliente escurrida.',
      'Servir con queso parmesano y decoración opcional.',
    ],
  },
  {
    id: '03',
    name: 'Carbonara',
    servings: 4,
    prepTimeMinutes: 30,
    ingredients: [
      { name: 'espaguetis', quantity: 400, unit: 'g' },
      { name: 'guanciale (o panceta)', quantity: 200, unit: 'g' },
      { name: 'yemas (o yemas + huevos enteros)', quantity: 8, unit: 'unidad' },
      { name: 'pecorino rallado', quantity: 200, unit: 'g' },
      {
        name: 'pimienta negra recién molida',
        unit: 'al gusto',
      },
    ],
    instructions: [
      'Cocer la pasta 1 minuto menos del tiempo indicado.',
      'Cortar el guanciale y dorarlo en sartén a fuego bajo hasta crocante.',
      'Batir las yemas con el queso y pimienta. Agregar agua de cocción si es necesario.',
      'Con el fuego apagado, agregar la pasta al sartén del guanciale, luego la mezcla de yemas y queso y un poco de agua de cocción.',
      'Mezclar rápidamente hasta obtener una salsa cremosa.',
      'Servir con pimienta negra recién molida.',
    ],
  },
  {
    id: '04',
    name: 'Boloñesa',
    servings: 3,
    prepTimeMinutes: 40,
    ingredients: [
      { name: 'espaguetis', quantity: 250, unit: 'g' },
      { name: 'carne molida de res', quantity: 250, unit: 'g' },
      { name: 'cebolla, picada', quantity: 1, unit: 'unidad' },
      { name: 'dientes de ajo, picados', quantity: 2, unit: 'unidad' },
      { name: 'zanahoria rallada', quantity: 1, unit: 'unidad' },
      { name: 'tomates triturados', quantity: 400, unit: 'g' },
      { name: 'orégano seco', quantity: 1, unit: 'cucharadita' },
      { name: 'albahaca seca', quantity: 1, unit: 'cucharadita' },
      { name: 'sal', unit: 'al gusto' },
      { name: 'pimienta', unit: 'al gusto' },
      { name: 'aceite de oliva', unit: 'al gusto' },
      { name: 'queso parmesano rallado', unit: 'al gusto' },
    ],
    instructions: [
      'Cocer los espaguetis y reservar.',
      'Saltear cebolla y ajo en aceite de oliva.',
      'Agregar carne molida y dorar, luego añadir zanahoria.',
      'Verter tomates, orégano, albahaca, sal y pimienta. Cocinar a fuego bajo 10-15 min.',
      'Servir la pasta con salsa boloñesa y queso parmesano por encima.',
    ],
  },
];
