import { DifficultyLevel, Recipe } from '@recipes/entities';

export const RECIPES_MOCK: Array<Recipe> = [
  {
    id: '01',
    name: 'Amatriciana',
    servings: 4,
    prepTimeMinutes: 35,
    difficultyLevel: DifficultyLevel.LOW,
    imgPath: '/assets/amatriciana.webp',
    ingredients: [
      { name: 'guanciale (o panceta ahumada)', quantity: '200 gr' },
      { name: 'pasta (bucatini es la opción tradicional)', quantity: '400 gr' },
      {
        name: 'tomates pelados en lata (o tomates cherry frescos)',
        quantity: '400 gr',
      },
      {
        name: 'cebolla pequeña o media cebolla grande, finamente picada (opcional)',
        quantity: '1 unidad',
      },
      { name: 'vino blanco', quantity: '50 ml' },
      { name: 'guindilla entera (opcional)', quantity: '1 unidad' },
      { name: 'aceite de oliva virgen extra (opcional)', quantity: 'a gusto' },
      { name: 'sal', quantity: 'a gusto' },
      {
        name: 'pecorino romano rallado (preferible) o Parmigiano-Reggiano',
        quantity: 'a gusto',
      },
    ],
    instructions: [
      'Cortar el guanciale (o la panceta) en tiras finas.',
      'Calentar una sartén sin aceite y agregar el guanciale. Cocinar a fuego medio hasta que suelte su grasa y se dore ligeramente. Agregar la guindilla si se desea.',
      'Retirar el guanciale y dejar parte de la grasa para cocinar la cebolla con sal. Cocinar hasta transparente (5-7 min).',
      'Añadir el vino blanco y evaporar el alcohol completamente.',
      'Agregar los tomates triturados o cherry y cocinar (10-20 min según el tipo).',
      'Cocer la pasta al dente según el paquete.',
      'Reservar un poco de agua de cocción y añadir a la salsa para ligar.',
      'Agregar la pasta a la sartén con la salsa y mezclar bien.',
      'Servir con queso pecorino rallado.',
    ],
    isFavourite: false,
  },
  {
    id: '02',
    name: 'Pesto',
    servings: 4,
    prepTimeMinutes: 30,
    difficultyLevel: DifficultyLevel.LOW,
    imgPath: '/assets/pesto.webp',
    ingredients: [
      { name: 'espaguetis', quantity: '350 g' },
      { name: 'hojas de albahaca fresca', quantity: '2 tazas' },
      { name: 'queso parmesano rallado', quantity: '0.5 taza' },
      { name: 'piñones (o nueces)', quantity: 'cuarto de taza' },
      { name: 'dientes de ajo', quantity: '2 unidades' },
      { name: 'aceite de oliva extra virgen', quantity: 'media taza' },
      { name: 'sal', quantity: 'a gusto' },
      { name: 'pimienta negra molida', quantity: 'a gusto' },
    ],
    instructions: [
      'Hervir agua con sal y cocinar los espaguetis al dente.',
      'En procesador o mortero, mezclar albahaca, queso, piñones y ajo.',
      'Agregar el aceite en hilo fino hasta obtener una salsa homogénea. Salpimentar.',
      'Mezclar el pesto con la pasta caliente escurrida.',
      'Servir con queso parmesano y decoración opcional.',
    ],
    isFavourite: false,
  },
  {
    id: '03',
    name: 'Carbonara',
    servings: 4,
    prepTimeMinutes: 30,
    difficultyLevel: DifficultyLevel.LOW,
    imgPath: '/assets/carbonara.webp',
    ingredients: [
      { name: 'espaguetis', quantity: '400 gr' },
      { name: 'guanciale (o panceta)', quantity: '200 gr' },
      { name: 'yemas (o yemas + huevos enteros)', quantity: '8 unidades' },
      { name: 'pecorino rallado', quantity: '200 gr' },
      { name: 'pimienta negra recién molida', quantity: 'a gusto' },
    ],
    instructions: [
      'Cocer la pasta 1 minuto menos del tiempo indicado.',
      'Cortar el guanciale y dorarlo en sartén a fuego bajo hasta crocante.',
      'Batir las yemas con el queso y pimienta. Agregar agua de cocción si es necesario.',
      'Con el fuego apagado, agregar la pasta al sartén del guanciale, luego la mezcla de yemas y queso y un poco de agua de cocción.',
      'Mezclar rápidamente hasta obtener una salsa cremosa.',
      'Servir con pimienta negra recién molida.',
    ],
    isFavourite: false,
  },
  {
    id: '04',
    name: 'Boloñesa',
    servings: 3,
    prepTimeMinutes: 40,
    difficultyLevel: DifficultyLevel.LOW,
    imgPath: '/assets/bolonesa.webp',
    ingredients: [
      { name: 'espaguetis', quantity: '250 gr' },
      { name: 'carne molida de res', quantity: '250 gr' },
      { name: 'cebolla, picada', quantity: '1 unidad' },
      { name: 'dientes de ajo, picados', quantity: '2 unidades' },
      { name: 'zanahoria rallada', quantity: '1 unidad' },
      { name: 'tomates triturados', quantity: '400 gr' },
      { name: 'orégano seco', quantity: '1 cucharadita' },
      { name: 'albahaca seca', quantity: '1 cucharadita' },
      { name: 'sal', quantity: 'a gusto' },
      { name: 'pimienta', quantity: 'a gusto' },
      { name: 'aceite de oliva', quantity: 'a gusto' },
      { name: 'queso parmesano rallado', quantity: 'a gusto' },
    ],
    instructions: [
      'Cocer los espaguetis y reservar.',
      'Saltear cebolla y ajo en aceite de oliva.',
      'Agregar carne molida y dorar, luego añadir zanahoria.',
      'Verter tomates, orégano, albahaca, sal y pimienta. Cocinar a fuego bajo 10-15 min.',
      'Servir la pasta con salsa boloñesa y queso parmesano por encima.',
    ],
    isFavourite: false,
  },
  {
    id: '05',
    name: 'Fettuccini Alfredo',
    servings: 8,
    prepTimeMinutes: 20,
    difficultyLevel: DifficultyLevel.LOW,
    imgPath: '/assets/alfredo.webp',
    ingredients: [
      { name: 'fettuccini', quantity: '500 gr' },
      { name: 'crema de leche', quantity: '2 tazas y media' },
      { name: 'mantequilla', quantity: '170 gr' },
      { name: 'jugo de limón', quantity: 'media taza' },
      { name: 'queso parmesano', quantity: '2 tazas' },
      { name: 'cáscara de limón', quantity: '2 cucharaditas' },
      { name: 'nuez moscada molida', quantity: '1 pizca' },
      { name: 'sal', quantity: 'a gusto' },
      { name: 'pimienta negra molida', quantity: 'a gusto' },
    ],
    instructions: [
      'Cocinar la pasta en una olla grande con agua salada hirviendo durante 4 minutos, hasta que esté tierna pero firme. Colar y reservar.',
      'En una sartén, colocar 2 tazas de crema de leche y el jugo de limón, mezclando bien.',
      'Agregar la mantequilla y cocinar a fuego medio hasta que se derrita completamente.',
      'Retirar del fuego, añadir la pasta y mezclar bien.',
      'Incorporar la 1/2 taza de crema restante y el queso parmesano a la salsa.',
      'Agregar la cáscara de limón, la nuez moscada, la sal y la pimienta.',
      'Colocar nuevamente la pasta a fuego lento hasta que la salsa espese ligeramente.',
      'Apagar el fuego y servir inmediatamente.',
    ],
    isFavourite: false,
  },
  {
    id: '06',
    name: 'Cacio e pepe',
    servings: 4,
    prepTimeMinutes: 20,
    difficultyLevel: DifficultyLevel.LOW,
    imgPath: '/assets/cacio-e-pepe.webp',
    ingredients: [
      { name: 'spaghetti o tonnarelli', quantity: '400 gr' },
      {
        name: 'queso rallado (pecorino romano, parmesano o grana padano)',
        quantity: '200 gr',
      },
      { name: 'pimienta negra recién molida', quantity: '1 cucharada' },
      { name: 'agua de cocción de la pasta', quantity: '2 tazas' },
      { name: 'sal', quantity: 'a gusto' },
    ],
    instructions: [
      'Poner a hervir abundante agua en una olla grande con un poco de sal. Cuando hierva, añadir la pasta y cocinar al dente (8-10 minutos). Reservar 2 tazas del agua de cocción antes de colar.',
      'Tostar la pimienta negra en una sartén grande a fuego medio durante un par de minutos. Reservar.',
      'En un bol grande, colocar el queso rallado y añadir un poco del agua de cocción caliente (no hirviendo). Batir hasta obtener una crema suave y sin grumos, agregando más agua si es necesario.',
      'Añadir la pasta cocida a la crema de queso y mezclar rápidamente. Agregar más agua de cocción si está seca para lograr una textura cremosa.',
      'Espolvorear la pimienta tostada sobre la pasta y mezclar bien.',
      'Servir inmediatamente.',
    ],
    isFavourite: false,
  },
  {
    id: '07',
    name: 'Salsa Scarparo',
    servings: 4,
    prepTimeMinutes: 30,
    difficultyLevel: DifficultyLevel.MEDIUM,
    imgPath: '/assets/scarparo.webp',
    ingredients: [
      { name: 'panceta en tiras', quantity: '150 gr' },
      { name: 'jamón en tiras (opcional)', quantity: '100 gr' },
      { name: 'cebolla de verdeo picada', quantity: '1 unidad' },
      { name: 'vino blanco (opcional)', quantity: 'medio vaso' },
      { name: 'ajo picado (opcional)', quantity: '1 diente' },
      { name: 'crema de leche', quantity: '1 taza' },
      { name: 'salsa de tomate', quantity: '1 taza' },
      { name: 'albahaca fresca picada', quantity: '1 puñado' },
      { name: 'queso rallado', quantity: 'media taza' },
      { name: 'aceite de oliva', quantity: 'a gusto' },
      { name: 'sal', quantity: 'a gusto' },
      { name: 'pimienta', quantity: 'a gusto' },
    ],
    instructions: [
      'En una sartén grande, cocinar la panceta en tiras hasta que esté dorada y crujiente. Reservar.',
      'Añadir 1-2 cucharadas de aceite de oliva y saltear la cebolla de verdeo a fuego medio hasta que esté transparente.',
      'Incorporar el ajo picado en los últimos 30 segundos de cocción, cuidando que no se queme.',
      'Añadir el vino blanco (si se usa) y cocinar 1-2 minutos para evaporar el alcohol.',
      'Agregar la salsa de tomate, mezclar y cocinar 5 minutos para integrar sabores.',
      'Incorporar la panceta reservada, el jamón (si se usa) y la crema de leche. Cocinar a fuego bajo 3-5 minutos hasta que espese ligeramente.',
      'Apagar el fuego y añadir el queso rallado, mezclando hasta fundir.',
      'Agregar la albahaca fresca picada antes de servir. Sazonar con sal y pimienta al gusto.',
      'Servir caliente sobre pasta recién cocida.',
    ],
    isFavourite: false,
  },
  {
    id: '08',
    name: 'Cavatelli',
    servings: 3,
    prepTimeMinutes: 60,
    difficultyLevel: DifficultyLevel.MEDIUM,
    imgPath: '/assets/cavatelli.webp',
    ingredients: [
      { name: 'sémola (o semolín fino)', quantity: '250 gr' },
      { name: 'agua tibia', quantity: '120 ml' },
      { name: 'sal', quantity: 'media cucharadita' },
      { name: 'ricota fresca bien escurrida (opcional)', quantity: '100 gr' },
      { name: 'harina común para espolvorear', quantity: 'a gusto' },
    ],
    instructions: [
      'Mezclar la sémola con la sal en un bol grande. Si se usa ricota, incorporarla ahora, bien escurrida.',
      'Agregar el agua tibia poco a poco mientras se mezcla hasta formar una masa. Ajustar la cantidad de agua si se usó ricota.',
      'Amasar sobre la mesada durante 10 minutos hasta lograr una masa firme y suave. Tapar con un paño y dejar reposar 30 minutos a temperatura ambiente.',
      'Dividir la masa en porciones y formar rollitos finos. Cortar en trozos de 1,5 cm y dar forma arrastrando con el dedo, un tenedor o tabla de ñoquis.',
      'Colocar la pasta en una bandeja espolvoreada con harina. Cubrir con un paño si no se cocina de inmediato o congelar.',
      'Cocinar en agua hirviendo con sal hasta que floten (2-3 minutos).',
      'Servir con la salsa elegida.',
    ],
    isFavourite: false,
  },
  {
    id: '09',
    name: 'Canelones de Acelga',
    servings: 12,
    prepTimeMinutes: 40,
    difficultyLevel: DifficultyLevel.HIGH,
    imgPath: '/assets/canelones-acelga.webp',
    ingredients: [
      { name: 'acelga', quantity: '1000 gr' },
      { name: 'ricota', quantity: '500 gr' },
      { name: 'huevo', quantity: '2 unidades' },
      { name: 'queso rallado', quantity: '100 gr' },
      { name: 'mozzarella rallada', quantity: '100 gr' },
      { name: 'nuez moscada', quantity: 'a gusto' },
      { name: 'sal', quantity: 'a gusto' },
      { name: 'pimienta', quantity: 'a gusto' },
      { name: 'panqueques para canelones', quantity: '12 unidades' },
      { name: 'salsa a elección', quantity: 'a gusto' },
    ],
    instructions: [
      'Hervir la acelga durante 3-5 minutos. Escurrir bien y picar finamente.',
      'En un bol, mezclar la acelga picada con la ricota, los huevos, 3/4 del queso rallado, la mozzarella rallada y los condimentos.',
      'Rellenar los panqueques con la mezcla y enrollar para formar los canelones.',
      'Colocar los canelones en una fuente para horno, cubrir con la salsa elegida y espolvorear con el queso rallado restante.',
      'Hornear a 180°C durante 15-20 minutos o hasta que estén gratinados.',
    ],
    isFavourite: false,
  },
  {
    id: '10',
    name: 'Ñoquis de Calabaza Rellenos',
    servings: 2,
    prepTimeMinutes: 60,
    difficultyLevel: DifficultyLevel.HIGH,
    imgPath: '/assets/ñoquis-calabaza-rellenos.webp',
    ingredients: [
      { name: 'calabaza cortada en cubos', quantity: '2 tazas' },
      { name: 'papa pelada y cortada en cubos', quantity: 'media taza' },
      { name: 'harina', quantity: '1 taza' },
      { name: 'huevo', quantity: '1 unidad' },
      {
        name: 'tomates secos hidratados y picados (o pasta de tomate)',
        quantity: 'a gusto',
      },
      { name: 'cebolla deshidratada', quantity: 'a gusto' },
      { name: 'sal', quantity: 'a gusto' },
      { name: 'pimienta', quantity: 'a gusto' },
      { name: 'nuez moscada', quantity: 'a gusto' },
      { name: 'ajo', quantity: 'a gusto' },
      { name: 'manteca', quantity: 'a gusto' },
      { name: 'aceite', quantity: 'a gusto' },
      { name: 'curry', quantity: 'a gusto' },
      { name: 'cebolla crispy', quantity: '2 cucharadas' },
      { name: 'tomillo', quantity: 'media cucharada' },
      { name: 'queso', quantity: '4 cucharadas' },
      { name: 'tomate seco', quantity: '6 unidades' },
      { name: 'agua del tomate', quantity: 'a gusto' },
      { name: 'crema', quantity: 'a gusto' },
      { name: 'cebolla verde', quantity: 'a gusto' },
    ],
    instructions: [
      'Cocinar la calabaza y la papa hasta que estén blandas. Hacer un puré y sazonar con sal y pimienta.',
      'Añadir el huevo y luego incorporar la harina gradualmente hasta formar una masa no pegajosa. Dejar reposar.',
      'Preparar el relleno mezclando tomates secos picados, cebolla deshidratada, tomillo y queso. Agregar un poco de agua si es necesario hasta obtener una pasta.',
      'Tomar porciones de masa, aplanar y colocar relleno en el centro. Cerrar formando bolitas.',
      'Para la salsa, calentar manteca y aceite en una sartén, freír ajo picado con curry hasta dorar. Reservar.',
      'Hervir los ñoquis en agua hasta que floten, luego cocinar 2 minutos más y escurrir.',
      'Añadir la crema a la sartén con el ajo y curry, calentar y agregar los ñoquis. Mezclar suavemente.',
      'Servir caliente con queso adicional y cebolla verde por encima.',
    ],
    isFavourite: false,
  },
  {
    id: '11',
    name: 'Lasaña de verduras',
    servings: 6,
    prepTimeMinutes: 45,
    difficultyLevel: DifficultyLevel.HIGH,
    imgPath: '/assets/lasaña-verduras.webp',
    ingredients: [
      { name: 'láminas de pasta para lasaña', quantity: '12 unidades' },
      { name: 'berenjena', quantity: '2 unidades grandes' },
      { name: 'zucchini (calabacín)', quantity: '2 unidades' },
      { name: 'salsa de tomate', quantity: '2 tazas' },
      { name: 'queso mozzarella', quantity: '200 gr' },
      { name: 'ricotta', quantity: '200 gr' },
      { name: 'queso parmesano rallado', quantity: '50 gr' },
      { name: 'aceite de oliva', quantity: 'a gusto' },
      { name: 'sal', quantity: 'a gusto' },
      { name: 'pimienta', quantity: 'a gusto' },
      {
        name: 'hierbas aromáticas (orégano, albahaca, etc.)',
        quantity: 'a gusto',
      },
    ],
    instructions: [
      'Precalentar el horno a 180°C. Lavar las berenjenas y los zucchini y cortarlos en rodajas finas.',
      'En una sartén grande, calentar aceite de oliva y saltear las rodajas de berenjena y zucchini hasta que estén tiernas. Reservar.',
      'Mezclar la ricotta con sal y pimienta en un bol.',
      'En una fuente para horno, colocar un poco de salsa de tomate, luego una capa de pasta, una capa de berenjena y zucchini, otra capa de salsa, otra de pasta y luego ricotta. Repetir el proceso hasta terminar los ingredientes, finalizando con salsa de tomate.',
      'Cubrir con queso mozzarella y queso parmesano rallado.',
      'Hornear 25-30 minutos hasta que la parte superior esté dorada.',
      'Dejar reposar unos minutos antes de servir y decorar con hierbas frescas.',
    ],
    isFavourite: false,
  },
  {
    id: '12',
    name: 'Agnolotis Caseros de Zapallo',
    servings: 2,
    prepTimeMinutes: 60,
    difficultyLevel: DifficultyLevel.MEDIUM,
    imgPath: '/assets/agnolotis-caseros.jpg',
    ingredients: [
      { name: 'masa para agnolotti', quantity: 'cantidad necesaria' },
      { name: 'zapallo', quantity: 'media unidad' },
      { name: 'cebolla', quantity: '1 unidad' },
      { name: 'morrón', quantity: '1 unidad' },
      { name: 'ajo', quantity: '1 unidad' },
      { name: 'tomate triturado', quantity: '2 cucharadas' },
      { name: 'queso rallado', quantity: '100 gr' },
      { name: 'aceite de oliva', quantity: 'a gusto' },
      { name: 'nuez moscada', quantity: 'a gusto' },
      { name: 'sal', quantity: 'a gusto' },
      { name: 'huevo batido', quantity: 'cantidad necesaria' },
    ],
    instructions: [
      'En una sartén con un poco de aceite, saltear cebolla picada, morrón picado, ajo y tomate triturado.',
      'Cocinar el zapallo hasta que esté blando, hacer un puré y unirlo con el sofrito. Saltear unos minutos más para eliminar exceso de líquido.',
      'Retirar del fuego, dejar enfriar y añadir sal, queso rallado y nuez moscada.',
      'Estirar la masa, humedecer los bordes con huevo batido y colocar una cucharada de relleno en el centro. Cerrar uniendo los bordes y reservar. Repetir hasta terminar el relleno.',
      'Hervir abundante agua, agregar sal y cocinar los agnolotis durante 8-9 minutos.',
      'Servir calientes con la salsa deseada.',
    ],
    isFavourite: false,
  },
];
